loomio_webhooks:
  repo:         loomio/loomio_webhooks

loomio_org_plugin:
  repo:         loomio/loomio_org_plugin
  branch:       move-assets-to-plugin

loomio_tags:
  repo:         loomio/loomio_tags
  branch:       tags-refactor
  experimental: true

loomio_truncate_comment:
  repo:         loomio/loomio_truncate_comment
  experimental: true

loomio_group_progress_card:
  repo: loomio/loomio_group_progress_card

loomio_content_preview:
  repo:         gdpelican/loomio_content_preview
  experimental: true
